name: Build SingleFile
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      BUILD_TYPE: REL
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Unpack git objects
        run: |
          mv .git/objects/pack .
          git unpack-objects < pack/*.pack
          rm -rf pack
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - uses: pnpm/action-setup@v2
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build:singlefile      
      - name: Rename
        run: mkdir dist/local && mv dist/index.html dist/local/cocogoat-web-local.html
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: cocogoat-local
          path: dist/local/
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: cocogoat-web-report
          path: dist/report.html